#!/usr/bin/env python3
"""Export the Hex-Rays output stored in reverse/BGI.sqlite as plain C files.

Usage: python3 src/tools/export_decompiled.py [reverse/BGI.sqlite] [src]

The export is mechanical and lossless: pseudocode is written verbatim, one
block per function, ordered by address and grouped in 0x4000-byte address
windows.  Hand-recovered structure definitions live in src/include/ and are
applied by editing the files under src/engine/ (see src/README.md).
"""
import re
import sqlite3
import sys
from pathlib import Path

db = sqlite3.connect(sys.argv[1] if len(sys.argv) > 1 else "reverse/BGI.sqlite")
out = Path(sys.argv[2] if len(sys.argv) > 2 else "src")
raw = out / "raw"
raw.mkdir(parents=True, exist_ok=True)

WINDOW = 0x4000


def ea(text):
    return int(text, 16)


funcs = {
    ea(r[0]): r for r in db.execute(
        "select start_ea_hex,end_ea_hex,name,proto_1line from functions")
}
decomp = {
    ea(r[0]): r for r in db.execute(
        "select start_ea_hex,name,status,error,pseudocode from decompilations")
}

windows = {}
index_rows = []
failed = []
for addr in sorted(funcs):
    _, end, name, proto = funcs[addr]
    d = decomp.get(addr)
    status = d[2] if d else "missing"
    index_rows.append((addr, ea(end), name, status))
    base = addr - addr % WINDOW
    if status != "ok":
        failed.append((addr, name, status, d[3] if d else ""))
        body = f"// DECOMPILATION UNAVAILABLE ({status}): see disassembly at 0x{addr:08X}\n"
    else:
        body = d[4].rstrip() + "\n"
    head = f"// ===== {name} @ 0x{addr:08X}..0x{ea(end):08X} =====\n"
    windows.setdefault(base, []).append(head + body)

for base, blocks in sorted(windows.items()):
    path = raw / f"text_{base:06X}.c"
    path.write_text(
        '#include "../include/ida_prelude.h"\n'
        '#include "../include/globals.h"\n\n' + "\n".join(blocks))

(out / "raw" / "INDEX.csv").write_text(
    "address,end,name,decompilation\n" +
    "".join(f"0x{a:08X},0x{e:08X},{n},{s}\n" for a, e, n, s in index_rows))

# ---- globals.h -----------------------------------------------------------
strings = {ea(r[0]): r[1] for r in db.execute("select ea_hex,value from strings")}
seg = [(ea(r[0]), ea(r[1]), r[2]) for r in db.execute(
    "select start_ea_hex,end_ea_hex,name from segments")]


def segment_of(a):
    for s, e, n in seg:
        if s <= a < e:
            return n
    return "?"


lines = ["// Data symbols of Tayutama2_trial_TG.exe (image base 0x400000).",
         "// Generated by src/tools/export_decompiled.py; sizes are guesses from the",
         "// IDA name prefix and are refined in src/include/engine_types.h.",
         '#include "ida_prelude.h"', ""]
decl = {
    "dword": "extern int {n};", "byte": "extern char {n};",
    "word": "extern short {n};", "flt": "extern float {n};",
    "qword": "extern long long {n};", "dbl": "extern double {n};",
    "unk": "extern char {n}[];", "off": "extern void *{n};",
    "stru": "extern char {n}[];", "asc": "extern char {n}[];",
}
seen_names = set()
for a, name in sorted((ea(r[0]), r[1]) for r in db.execute(
        "select ea_hex,name from names")):
    if a in funcs or segment_of(a) in (".text", ".idata", "?"):
        continue
    if name in seen_names or not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", name):
        continue
    seen_names.add(name)
    kind = re.match(r"([a-z]+)_", name)
    template = decl.get(kind.group(1) if kind else "", "extern char {n}[];")
    comment = f"  // 0x{a:08X} {segment_of(a)}"
    if a in strings:
        comment += "  \"" + strings[a].replace("\n", "\\n")[:60] + "\""
    lines.append(template.format(n=name) + comment)
# IDA auto-names (dword_565B70, unk_4E5264, off_503DEC ...) exist only inside
# the pseudocode, so collect them from there as well.
auto = re.compile(r"\b(dword|byte|word|qword|flt|dbl|unk|off|stru|asc)_([0-9A-F]{6,8})\b")
for d in decomp.values():
    for kind, hexa in auto.findall(d[4] or ""):
        name = f"{kind}_{hexa}"
        if name in seen_names:
            continue
        seen_names.add(name)
        a = int(hexa, 16)
        lines.append(decl[kind].format(n=name) + f"  // 0x{a:08X} {segment_of(a)}")
inc = out / "include"
inc.mkdir(exist_ok=True)
(inc / "globals.h").write_text("\n".join(lines) + "\n")

(raw / "FAILED.txt").write_text("".join(
    f"0x{a:08X} {n} {s} {e}\n" for a, n, s, e in failed))
print(f"{len(index_rows)} functions in {len(windows)} files, "
      f"{len(failed)} without decompilation, {len(seen_names)} globals")
